added port-fowarding link, how to op/run commands, and "server cant keep up error"
mcserversoft/documentation pull request #11
Opened 2020-12-01 02:04 UTC by cyric2020

2020-12-06 18:58 UTC, vaio2005 approved these changes
All should be fine.

2021-03-06 09:36 UTC, Fiahblade commented
@cyric2020 Looks great, can you fix the conflicts so that I can merge it? Thanks!

2021-03-06 09:40 UTC, Fiahblade commented
Not sure if you noticed but there is a forge installation section: https://mcserversoft.github.io/documentation/create-forge-server/

2021-03-06 13:17 UTC, vaio2005 requested changes
Moved to another location and typo

2021-03-06 13:17 UTC, vaio2005 commented on docs/minecraft-faq.md
> +<a name=""server-cant-keep-up></a>
Misspell

2021-03-06 13:17 UTC, vaio2005 commented on docs/minecraft-faq.md
> +Forge installation is a bit more complicated than any other server type because forge needs some libraries to run.
Moved to https://mcserversoft.github.io/documentation/create-forge-server/

2021-06-17 11:44 UTC, Leonito2003 commented
minecraft-faq doesn't exist anymore, and the forge guide has its own page now

2021-06-17 11:44 UTC, closed without merging