Added "Failed To Bind To Port" Section to the FAQ
mcserversoft/documentation pull request #8
Opened 2020-11-29 11:06 UTC by stefmmm

2020-11-30 08:29 UTC, stefmmm commented
Needs Reworking

2020-11-30 08:51 UTC, stefmmm commented
Dunno whether this will include my new changes but here goes.

2021-03-06 13:27 UTC, vaio2005 requested changes
Little change, not something big

2021-03-06 13:27 UTC, vaio2005 commented on docs/faq.md
> +*   [Failed to bind to port](#failed-to-bind-to-port)
All this part needs to be removed to comply with #17

2021-03-06 13:31 UTC, vaio2005 commented on docs/faq.md
> +*   [Failed to bind to port](#failed-to-bind-to-port)
Might want to wait for this. Other change could be required based on #17

2021-03-06 13:52 UTC, stefmmm commented
Okay sounds good just let me know once you know more.

Sent from ProtonMail mobile

-------- Original Message --------
On 6 Mar 2021, 14:31, filliravaz wrote:

> @vaio2005 commented on this pull request.
>
> ---------------------------------------------------------------
>
> In [docs/faq.md](https://github.com/mcserversoft/documentation/pull/8#discussion_r588882770):
>
>> @@ -5,6 +5,7 @@
>  *   [Error occurred during initialization of VM Could not reserve enough space for 2097152KB object heap.](#error-occurred-during-initialization-of-vm)
>  *   [My server keeps saying starting.](#server-keeps-saying-starting)
>  *   [Unable to connect to the server.](#unable-to-connect-to-the-server)
> +*   [Failed to bind to port](#failed-to-bind-to-port)
>
> Might want to wait for this. Other change could be required based on [#17](https://github.com/mcserversoft/documentation/pull/17)
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, [view it on GitHub](https://github.com/mcserversoft/documentation/pull/8#discussion_r588882770), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AISBXPBIJNIX4R2TGSV53WTTCIVCLANCNFSM4UGN55NQ).

2021-06-22 18:02 UTC, Fiahblade commented
@stefmmm Thanks!

2021-06-22 18:02 UTC, merged